M48
; DRILL file {KiCad (6.0.10)} date Wed Feb  1 10:46:19 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T10:46:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.2717Y-2.1575
X4.2717Y-3.2205
X6.0433Y-2.1575
X6.0433Y-3.2205
T2
X4.6791Y-2.3602
X5.748Y-3.4094
T0
M30
