@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jan 03 14:25:16 +0100 2022
REM SW Build 2960000 on Wed Aug  5 22:57:20 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim spi_readout_test_tb_behav -key {Behavioral:spi_tb:Functional:spi_readout_test_tb} -tclbatch spi_readout_test_tb.tcl -view C:/Users/nicolas/Documents/GitHub/astropix_github/FW/AstroPix2/spi_readout_test_tb_behav.wcfg -view C:/Users/nicolas/Documents/GitHub/astropix_github/FW/AstroPix2/spi_readout_test_tb_behav1.wcfg -log simulate.log"
call xsim  spi_readout_test_tb_behav -key {Behavioral:spi_tb:Functional:spi_readout_test_tb} -tclbatch spi_readout_test_tb.tcl -view C:/Users/nicolas/Documents/GitHub/astropix_github/FW/AstroPix2/spi_readout_test_tb_behav.wcfg -view C:/Users/nicolas/Documents/GitHub/astropix_github/FW/AstroPix2/spi_readout_test_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
