M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fr 29 Sep 2023 12:01:05 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-29T12:01:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X108.5Y-54.8
X108.5Y-81.8
X153.5Y-54.8
X153.5Y-81.8
T2
X118.85Y-59.95
X145.4Y-87.1
T0
M30
